exclude_patterns:
- "docs/"
- "Tests/"
- ".nyc_output/"
- ".showroom/"
- "coverage/"
- "NightWatch.tests/"
- "node_modules/"
- "Utils/"
- "*.png"
- ".*"
- "commitlint.config.js"
- "local.runner.js"
- "local.server.js"
- "nightwatch.conf.js"
- "package-lock.json"
- "package.json"
